export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const POST_LOADING = 'POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';

//Master types
//Company
export const COMPANY_LOADING = "COMPANY_LOADING";
export const GET_COMPANY = "GET_COMPANY";
export const ADD_COMPANY = "ADD_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const GET_CURRENT_COMPANY = "GET_CURRENT_COMPANY";


//Product
export const GET_PRODUCT = 'GET_PRODUCT';
export const ADD_PRODUCT= 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const GET_CURRENT_PRODUCT = 'GET_CURRENT_PRODUCT';


//service
export const GET_SERVICE = 'GET_SERVICE';
export const ADD_SERVICE= 'ADD_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const SERVICE_LOADING = 'SERVICE_LOADING';
export const GET_CURRENT_SERVICE = 'GET_CURRENT_SERVICE';


//customer
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const ADD_CUSTOMER= 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const CUSTOMER_LOADING = 'CUSTOMER_LOADING';
export const GET_CURRENT_CUSTOMER = 'GET_CURRENT_CUSTOMER';

//customersubdepartment
export const GET_CUSTOMER_SUB_DEPARTMENT = 'GET_CUSTOMER_SUB_DEPARTMENT';
export const ADD_CUSTOMER_SUB_DEPARTMENT= 'ADD_CUSTOMER_SUB_DEPARTMENT';
export const DELETE_CUSTOMER_SUB_DEPARTMENT = 'DELETE_CUSTOMER_SUB_DEPARTMENT';
export const CUSTOMER_SUB_DEPARTMENT_LOADING = 'CUSTOMER_SUB_DEPARTMENT_LOADING';
export const GET_CURRENT_CUSTOMER_SUB_DEPARTMENT = 'GET_CURRENT_CUSTOMER_SUB_DEPARTMENT';

//Setting types
//calltype
export const GET_CALL_TYPE = "GET_CALL_TYPE";
export const ADD_CALL_TYPE = "ADD_CALL_TYPE";
export const DELETE_CALL_TYPE = "DELETE_CALL_TYPE";
export const CALL_TYPE_LOADING = "CALL_TYPE_LOADING";
export const GET_CURRENT_CALL_TYPE = "GET_CURRENT_CALL_TYPE";


//customertype
export const GET_CUSTOMER_TYPE = "GET_CUSTOMER_TYPE";
export const ADD_CUSTOMER_TYPE = "ADD_CUSTOMER_TYPE";
export const DELETE_CUSTOMER_TYPE = "DELETE_CUSTOMER_TYPE";
export const CUSTOMER_TYPE_LOADING = "CUSTOMER_TYPE_LOADING";
export const GET_CURRENT_CUSTOMER_TYPE = "GET_CURRENT_CUSTOMER_TYPE";

//designation
export const GET_DESIGNATION = "GET_DESIGNATION";
export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const DELETE_DESIGNATION = "DELETE_DESIGNATION";
export const DESIGNATION_LOADING = "DESIGNATION_LOADING";
export const GET_CURRENT_DESIGNATION = "GET_CURRENT_DESIGNATION";

//productcategory
export const GET_PRODUCT_CATEGORY = "GET_PRODUCT_CATEGORY";
export const ADD_PRODUCT_CATEGORY = "ADD_PRODUCT_CATEGORY";
export const DELETE_PRODUCT_CATEGORY = "DELETE_PRODUCT_CATEGORY";
export const  PRODUCT_CATEGORY_LOADING = "PRODUCT_CATEGORY_LOADING";
export const GET_CURRENT_PRODUCT_CATEGORY = "GET_CURRENT_PRODUCT_CATEGORY";

//productsubcategory
export const GET_PRODUCT_SUB_CATEGORY = "GET_PRODUCT_SUB_CATEGORY";
export const ADD_PRODUCT_SUB_CATEGORY = "ADD_PRODUCT_SUB_CATEGORY";
export const DELETE_PRODUCT_SUB_CATEGORY = "DELETE_PRODUCT_SUB_CATEGORY";
export const  PRODUCT_SUB_CATEGORY_LOADING = "PRODUCT_SUB_CATEGORY_LOADING";
export const GET_CURRENT_PRODUCT_SUB_CATEGORY = "GET_CURRENT_PRODUCT_SUB_CATEGORY"

//service provider
export const GET_SERVICE_PROVIDER = "GET_SERVICE_PROVIDER";
export const ADD_SERVICE_PROVIDER = "ADD_SERVICE_PROVIDER";
export const DELETE_SERVICE_PROVIDER = "DELETE_SERVICE_PROVIDER";
export const SERVICE_PROVIDER_LOADING = "SERVICE_PROVIDER_LOADING";
export const GET_CURRENT_SERVICE_PROVIDER = "GET_CURRENT_SERVICE_PROVIDER";

//speciality
export const GET_SPECIALITY = "GET_SPECIALITY";
export const ADD_SPECIALITY = "ADD_SPECIALITY";
export const DELETE_SPECIALITY = "DELETE_SPECIALITY";
export const SPECIALITY_LOADING = "SPECIALITYS_LOADING";
export const GET_CURRENT_SPECIALITY = "GET_CURRENT_SPECIALITY";
